package edu.brown.cs.cutlass;

import edu.brown.cs.cutlass.config.ConfigEngine;
import edu.brown.cs.cutlass.sys.io.AbstractIdentifier;
import edu.brown.cs.cutlass.util.Option;
import edu.brown.cs.cutlass.util.Pair;
import java.awt.Cursor;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gaurav Manek
 */
class FrmMain extends javax.swing.JFrame {

    private final Launcher launcher;
    private final ConfigEngine config;

    /**
     * Creates new main form.
     *
     * @param launcher
     * @param configEngine The configuration information is stored here.
     * @param optLaunchState The state to restore the program to, if one is
     * available, is stored here.
     */
    FrmMain(Launcher launcher, ConfigEngine configEngine, Option<LaunchState> optLaunchState) {
        initComponents();

        this.launcher = launcher;
        this.config = configEngine;

        //<editor-fold defaultstate="collapsed" desc="Load Toolbar Icons">
        // Load this dimension from configEngine:
        Dimension toolbarIconSize = config.getDimension("ui.toolbar.iconsize");
        List<Pair<JLabel, String>> labelIcons = Arrays.asList(new Pair<>(tbSave, "document-save-5.png"), new Pair<>(tbRun, "arrow-right-3.png"), new Pair<>(tbAutoIndent, "format-indent-more-3.png"), new Pair<>(tbBookmarkStop, "dialog-cancel-5.png"), new Pair<>(tbRedo, "edit-redo-3.png"), new Pair<>(tbUndo, "edit-undo-3.png"), new Pair<>(tbBookmarkBack, "arrow-up-double.png"), new Pair<>(tbBookmarkSet, "bookmark-2.png"), new Pair<>(tbBookmarkNext, "arrow-down-double.png"));
        for (Pair<JLabel, String> p : labelIcons) {
            JLabel lbl = p.getX();
            lbl.setText("");
            lbl.setMinimumSize(toolbarIconSize);
            lbl.setPreferredSize(toolbarIconSize);
            lbl.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            
            ImageIcon tmpImg = new ImageIcon(getClass().getResource("/edu/brown/cs/cutlass/assets/icons/" + p.getY()));
            
            // Calculate the dimensions
            Dimension thisIconSize = null;//new Dimension(tmpImg.getIconWidth(), tmpImg.getIconHeight());
            // If the icon is larger than the space for it in at least one dimension, resize it:
            if (tmpImg.getIconHeight() > toolbarIconSize.height || tmpImg.getIconWidth() > toolbarIconSize.width) {
                float aspectRatio = tmpImg.getIconHeight() * 1.0f / tmpImg.getIconWidth(); // Height/Width
                int tmpHeight = Math.round(aspectRatio * toolbarIconSize.width);
                // If the width is not the limiting dimension:
                if (tmpHeight > toolbarIconSize.height) {
                    thisIconSize = new Dimension(Math.round(toolbarIconSize.height / aspectRatio), toolbarIconSize.height);
                } else {
                    thisIconSize = new Dimension(toolbarIconSize.width, tmpHeight);
                }
            }
            
            // If we don't need to resize the icon:
            if (thisIconSize == null) {
                lbl.setIcon(tmpImg);
            } else {
                lbl.setIcon(new ImageIcon(tmpImg.getImage().getScaledInstance(thisIconSize.width, thisIconSize.height, java.awt.Image.SCALE_SMOOTH)));
            }
        }
//</editor-fold>
        
        if(optLaunchState.hasData()){
            LaunchState launchState = optLaunchState.getData();
            // Load data from the launchState
        } else {
            // Load default
            tabEditors.addTab("Default", new PnlDefaultEditor());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spltPrimary = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        tabEditors = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        tbSave = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        tbRun = new javax.swing.JLabel();
        tbBookmarkStop = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        tbUndo = new javax.swing.JLabel();
        tbRedo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tbAutoIndent = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tbBookmarkBack = new javax.swing.JLabel();
        tbBookmarkSet = new javax.swing.JLabel();
        tbBookmarkNext = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuEdit = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();
        mnuHelpAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cutlass - Your Weapon of Choice");
        setMinimumSize(new java.awt.Dimension(400, 120));
        setPreferredSize(new java.awt.Dimension(500, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        spltPrimary.setDividerLocation(300);
        spltPrimary.setResizeWeight(1.0);

        jPanel2.setMinimumSize(new java.awt.Dimension(250, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 665));

        jList1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "BinaryTree (data)", "tree-to-list (fun)", "is-sorted (fun)", "is-bst (fun)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel1.setText("Quick Navigation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );

        spltPrimary.setRightComponent(jPanel2);

        tabEditors.setMinimumSize(new java.awt.Dimension(450, 100));
        spltPrimary.setLeftComponent(tabEditors);

        getContentPane().add(spltPrimary, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(383, 42));

        tbSave.setText("[Icon]");
        tbSave.setName(""); // NOI18N
        tbSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSaveMouseClicked(evt);
            }
        });
        jToolBar1.add(tbSave);
        jToolBar1.add(jSeparator1);

        tbRun.setText("[Icon]");
        tbRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRunMouseClicked(evt);
            }
        });
        jToolBar1.add(tbRun);

        tbBookmarkStop.setText("[Icon]");
        tbBookmarkStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBookmarkStopMouseClicked(evt);
            }
        });
        jToolBar1.add(tbBookmarkStop);
        jToolBar1.add(jSeparator3);

        tbUndo.setText("[Icon]");
        tbUndo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUndoMouseClicked(evt);
            }
        });
        jToolBar1.add(tbUndo);

        tbRedo.setText("[Icon]");
        tbRedo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRedoMouseClicked(evt);
            }
        });
        jToolBar1.add(tbRedo);
        jToolBar1.add(jSeparator2);

        tbAutoIndent.setText("[Icon]");
        tbAutoIndent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAutoIndentMouseClicked(evt);
            }
        });
        jToolBar1.add(tbAutoIndent);
        jToolBar1.add(jSeparator4);

        tbBookmarkBack.setText("[Icon]");
        tbBookmarkBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBookmarkBackMouseClicked(evt);
            }
        });
        jToolBar1.add(tbBookmarkBack);

        tbBookmarkSet.setText("[Icon]");
        tbBookmarkSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBookmarkSetMouseClicked(evt);
            }
        });
        jToolBar1.add(tbBookmarkSet);

        tbBookmarkNext.setText("[Icon]");
        tbBookmarkNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBookmarkNextMouseClicked(evt);
            }
        });
        jToolBar1.add(tbBookmarkNext);
        jToolBar1.add(jSeparator5);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        mnuFile.setText("File");
        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Edit");
        jMenuBar1.add(mnuEdit);

        mnuHelp.setText("Help");

        mnuHelpAbout.setText("About");
        mnuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHelpAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSaveMouseClicked

    private void tbRunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRunMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRunMouseClicked

    private void tbBookmarkStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBookmarkStopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBookmarkStopMouseClicked

    private void tbUndoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUndoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbUndoMouseClicked

    private void tbRedoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRedoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRedoMouseClicked

    private void tbAutoIndentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAutoIndentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAutoIndentMouseClicked

    private void tbBookmarkBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBookmarkBackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBookmarkBackMouseClicked

    private void tbBookmarkSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBookmarkSetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBookmarkSetMouseClicked

    private void tbBookmarkNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBookmarkNextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBookmarkNextMouseClicked
    
    private void mnuHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpAboutActionPerformed
        JOptionPane.showMessageDialog(this,
                "Cutlass - Pyret IDE\n" +
                "For CSCI 0320 Spring 2014, Term Project\n" +
                "By: Dilip Arumugam, Gaurav Manek,\n" +
                "      Miles Holland, Zachary Zagorski",
                "About", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_mnuHelpAboutActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        launcher.quit(LaunchState.toState(new ArrayList<AbstractIdentifier>(), 0));
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHelpAbout;
    private javax.swing.JSplitPane spltPrimary;
    private javax.swing.JTabbedPane tabEditors;
    private javax.swing.JLabel tbAutoIndent;
    private javax.swing.JLabel tbBookmarkBack;
    private javax.swing.JLabel tbBookmarkNext;
    private javax.swing.JLabel tbBookmarkSet;
    private javax.swing.JLabel tbBookmarkStop;
    private javax.swing.JLabel tbRedo;
    private javax.swing.JLabel tbRun;
    private javax.swing.JLabel tbSave;
    private javax.swing.JLabel tbUndo;
    // End of variables declaration//GEN-END:variables
}
